/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dio.cognizant21.desafio1;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertFalse;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class BancoTest {
    Banco banco;

    @BeforeEach
    void setUp() {
        banco = new Banco("Banco Teste");
    }

    @Test
    void verificarNomeDoBanco() {
        assertEquals("Banco Teste", banco.getNome());
    }

    @Test
    void cadastroSucesso() {
        assertTrue(banco.cadastrarCliente("Joao da Silva"));
    }
    
    @Test
    void cadastroFracasso() {
        banco.cadastrarCliente("Joao da Silva");
        assertFalse(banco.cadastrarCliente("Joao da Silva"));
    }

    @Test
    void descadastroSucesso() {
        banco.cadastrarCliente("Joao da Silva");
        assertTrue(banco.descadastrarCliente("Joao da Silva"));
    }

    @Test
    void descadastroFracasso() {
        assertFalse(banco.descadastrarCliente("Joao da Silva"));
    }
    
}
